# Generated by Django 4.2.11 on 2026-02-05 09:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('ceiling_fan', 'Ceiling Fan'), ('pedestal_fan', 'Pedestal Fan'), ('bracket_fan', 'Bracket Fan'), ('exhaust_fan', 'Exhaust Fan'), ('air_cooler', 'Air Cooler'), ('washing_machine', 'Washing Machine'), ('dryer', 'Dryer'), ('air_purifier', 'Air Purifier'), ('geyser', 'Geyser')], max_length=20)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('image_local', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specifications', models.JSONField(default=dict)),
                ('features', models.JSONField(default=list)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['category'], name='api_product_categor_07b5d3_idx'), models.Index(fields=['is_active'], name='api_product_is_acti_b97ca3_idx'), models.Index(fields=['is_featured'], name='api_product_is_feat_fda764_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
